trigger: none

parameters:  
  - name: environment
    displayName: Environment
    type: string
    default: 'tst'
  - name: workers
    displayName: Number of Workers
    type: string
    default: '10'
  - name: seleniumGrid
    displayName: Selenium Grid URL
    type: string
    default: 'http://localhost:4444'
  - name: deviceName
    displayName: Device Name
    type: string
    default: 'Windows'
  - name: bsOSVersion
    displayName: BrowserStack OS Version
    type: string
    default: '11'
  - name: bsBrowserVersion
    displayName: BrowserStack Browser Version
    type: string
    default: 'latest'
  - name: target
    displayName: Target Browser
    type: string
    default: 'Chrome'
  - name: isEmulationEnabled
    displayName: Enable Emulation
    type: string
    default: 'false'
  - name: emulateDeviceInfo
    displayName: Emulated Device Info
    type: string
    default: 'iPhone 12 Pro'
  - name: isAccessibilityTesting
    displayName: Enable Accessibility Testing
    type: string
    default: 'false'
  
schedules:
- cron: "0 02 * * Mon,Tue,Wed,Thu,Fri"
  displayName: Daily midnight build
  branches:
    include:
    - dev
    exclude:
    - feature/*
    - task/*
    - master

resources:
  repositories:
    - repository: PetsAutomationRepo
      type: git
      name: DEFRA-PET-TRAVEL/Defra.PTS.AutomationTests
      ref: $(Build.SourceBranch)


stages:
  
  - stage: PETS_AP_E2E
    displayName: PETS_AP_E2E

    variables:
      - template: 'variables/AP/${{parameters.environment}}.yml'

    jobs:
    
    - template: run-test-template.yml
      parameters:
        jobName: PETS_AP_E2E
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: ${{parameters.deviceName}}
        bsOSVersion: ${{parameters.bsOSVersion}}
        workers:  ${{parameters.workers}}
        bsBrowserVersion: 'latest'
        target: ${{parameters.target}}
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        isAccessibilityTesting: ${{parameters.isAccessibilityTesting}}
        application: 'AP'
        dependsOn: ''

    - template: generate-Specflow-Report.yml
      parameters:
        jobName: CreateSpecflowReport
        branchName: $(Build.SourceBranch)
        SeleniumGrid: ${{parameters.seleniumGrid}}
        dependsOn:
        - PETS_AP_E2E
        projects:
        - PETS_AP_E2E



