trigger:
  branches:
    exclude:
      - '*'

parameters:
  - name: branchName
    displayName: Branch Name
    type: string
    default: 'refs/heads/dev'
  - name: environment
    type: string
    default: 'pre'
  - name: workers
    displayName: Number of Workers
    type: string
    default: '10'
  - name: seleniumGrid
    displayName: Selenium Grid URL
    type: string
    default: 'https://hub.browserstack.com/wd/hub/'
  - name: isEmulationEnabled
    displayName: Enable Emulation
    type: string
    default: 'false'
  - name: emulateDeviceInfo
    displayName: Emulated Device Info
    type: string
    default: 'iPhone 12 Pro'

resources:
  repositories:
    - repository: niptsopsprovingrepo
      type: github
      name: DEFRA/nipts-pts-ops-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

stages:
  
  - stage: Android_SamsungGalaxyS23_Chrome
    displayName: SamsungGalaxyS23_Chrome
    variables:
        - template: 'variables/AP/${{ parameters.environment }}.yml'
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyS23_Chrome
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: 'Samsung Galaxy S23'
        bsOSVersion: '13.0'
        workers:  ${{parameters.workers}}
        bsBrowserVersion: '13.0'
        target: 'chrome'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'

  - stage: Android_SamsungGalaxyS23_SamsungInternet
    displayName: SamsungGalaxyS23_SamsungInternet
    variables:
        - template: 'variables/AP/${{ parameters.environment }}.yml'
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyS23_SamsungInternet
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: 'Samsung Galaxy S23'
        bsOSVersion: '13.0'
        workers:  ${{parameters.workers}}
        bsBrowserVersion: '13.0'
        target: 'samsung'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'

  - stage: Android_SamsungGalaxyTabS9_Chrome
    displayName: SamsungGalaxyTabS9_Chrome
    variables:
        - template: 'variables/AP/${{ parameters.environment }}.yml'
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyTabS9_Chrome
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: 'Samsung Galaxy Tab S9'
        bsOSVersion: '13.0'
        workers:  ${{parameters.workers}}
        bsBrowserVersion: '13.0'
        target: 'chrome'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'

  - stage: Android_SamsungGalaxyTabS9_SamsungInternet
    displayName: SamsungGalaxyTabS9_SamsungInternet
    variables:
        - template: 'variables/AP/${{ parameters.environment }}.yml'
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyTabS9_SamsungInternet
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: 'Samsung Galaxy Tab S9'
        bsOSVersion: '13.0'
        workers:  ${{parameters.workers}}
        bsBrowserVersion: '13.0'
        target: 'samsung'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'

  - stage: Android_OnePlus11R_Chrome
    displayName: OnePlus11R_Chrome
    variables:
        - template: 'variables/AP/${{ parameters.environment }}.yml'
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: OnePlus11R_Chrome
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: 'OnePlus 11R'
        bsOSVersion: '13.0'
        workers:  ${{parameters.workers}}
        bsBrowserVersion: '13.0'
        target: 'chrome'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'