trigger: none

parameters:
  - name: environment
    type: string
    default: 'pre'

resources:
  repositories:
    - repository: niptsopsprovingrepo
      type: github
      name: DEFRA/nipts-pts-ops-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

variables:
    - template: 'variables/AP/${{ parameters.environment }}.yml'

stages:
  
  - stage: OSX_Sequoia_Safari
    displayName: Sequoia_Safari
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: Sequoia_Safari
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/'
        deviceName: 'OS X'
        bsOSVersion: 'Sequoia'
        workers:  '10'
        bsBrowserVersion: '18.1'
        target: 'Safari'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'

  - stage: OSX_Sonama_Safari
    displayName: Sonama_Safari
    condition: always()
    jobs:
        
    - template: run-test-template.yml
      parameters:
        jobName: Sonama_Safari
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/'
        deviceName: 'OS X'
        bsOSVersion: 'Sonoma'
        workers:  '10'
        bsBrowserVersion: '17.3'
        target: 'Safari'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'

  - stage: OSX_Sonama_Firefox
    displayName: Sonama_Firefox
    condition: always()
    jobs:
        
    - template: run-test-template.yml
      parameters:
        jobName: Sonama_Firefox
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/'
        deviceName: 'OS X'
        bsOSVersion: 'Sonoma'
        workers:  '10'
        bsBrowserVersion: 'latest'
        target: 'Firefox'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'

  - stage: OSX_Sonama_Chrome
    displayName: Sonama_Chrome
    condition: always()
    jobs:
        
    - template: run-test-template.yml
      parameters:
        jobName: Sonama_Chrome
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/'
        deviceName: 'OS X'
        bsOSVersion: 'Sonoma'
        workers:  '10'
        bsBrowserVersion: 'latest'
        target: 'Chrome'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'AP'
        filterTestCases: 'TestCategory=APCrossBrowser'