trigger:
- master
- dev
- feature/*
- task/*
- release/*

pool:
    name: 'DEFRA-TRD'

variables:
  BuildConfiguration: Release

steps:


  - script: |
      echo "##vso[task.logissue type=error]Required: AzurePipelines.Agent.FilePathMapping.AgentIndex"
      $baseDir = "$(Build.SourceDirectory)"
      $files = Get-ChildItem -Path $baseDir -Recurse -File
      $folders = Get-ChildItem -Path $baseDir -Recurse -Directory
 
      Write-Host "Files:"
      foreach ($file in $files) {
        Write-Host $file.FullName
      }
 
      Write-Host "Folders:"
      foreach ($folder in $folders) {
        Write-Host $folder.FullName
      }

  - task: DotNetCoreCLI@2
    displayName: Restore for $(BuildConfiguration)
    inputs:
      command: 'restore'
      noCache: true
      projects: '**/Defra.UI.Tests.csproj'
      feedsToUse: 'config'
      includeNuGetOrg: true
      nugetConfigPath: $(Build.SourcesDirectory)/nipts-pts-ops-automation-tests/Defra.UI.Tests/NuGet.Config
  
  - task: DotNetCoreCLI@2
    displayName: publish for $(BuildConfiguration)
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/Defra.UI.Tests.csproj'
      arguments: --no-restore --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'