trigger:
- master
- dev
- feature/*
- task/*
- release/*

pool:
    name: 'DEFRA-TRD'

variables:
  BuildConfiguration: Release

steps:

  - task: Cache@2
    displayName: 'Clear Cache'
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
      path: '$(Pipeline.Workspace)/.nuget/packages'
      cacheHitVar: 'CACHE_RESTORED' 

  - task: DotNetCoreCLI@2
    displayName: Restore for $(BuildConfiguration)
    inputs:
      command: 'restore'
      projects: '**/Defra.UI.Tests.csproj'
      feedsToUse: 'config'
      includeNuGetOrg: true
      nugetConfigPath: 'nuget.config'
  
  - task: DotNetCoreCLI@2
    displayName: publish for $(BuildConfiguration)
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/Defra.UI.Tests.csproj'
      arguments: --no-restore --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'