trigger: none

parameters:
  - name: branchName
    displayName: Branch Name
    type: string
    default: 'refs/heads/dev'
  - name: environment
    type: string
    default: 'tst'
  - name: workers
    displayName: Number of Workers
    type: string
    default: '10'
  - name: seleniumGrid
    displayName: Selenium Grid URL
    type: string
    default: 'https://hub.browserstack.com/wd/hub/'
  - name: deviceName
    displayName: Device Name
    type: string
    default: 'Windows'
  - name: bsOSVersion
    displayName: BrowserStack OS Version
    type: string
    default: '11'
  - name: bsBrowserVersion
    displayName: BrowserStack Browser Version
    type: string
    default: 'latest'
  - name: target
    displayName: Target Browser
    type: string
    default: 'Chrome'
  - name: isEmulationEnabled
    displayName: Enable Emulation
    type: string
    default: 'false'
  - name: emulateDeviceInfo
    displayName: Emulated Device Info
    type: string
    default: 'iPhone 12 Pro'
  - name: isAccessibilityTesting
    displayName: Enable Accessibility Testing
    type: string
    default: 'false'

resources:
  repositories:
    - repository: PetsAutomationRepo
      type: git
      name: DEFRA-PET-TRAVEL/Defra.PTS.AutomationTests
      ref: $(Build.SourceBranch)

stages:
  
  - stage: Windows_Chrome_latest
    displayName: Windows_Chrome_latest    
    variables:
        - template: 'variables/${{ parameters.Environment }}.yml'
  
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: Windows_Chrome_latest
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: ${{parameters.deviceName}}
        bsOSVersion: ${{parameters.bsOSVersion}}
        workers:  ${{parameters.workers}}
        bsBrowserVersion: 'latest'
        target: 'Chrome'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        isAccessibilityTesting: ${{parameters.isAccessibilityTesting}}
        dependsOn: ''

    - template: generate-Specflow-Report.yml
      parameters:
        jobName: CreateSpecflowReport
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.seleniumGrid}}
        dependsOn:
        - Windows_Chrome_latest
        projects:
        - PETS_E2E

  - stage: Windows_Edge
    displayName: Windows_Edge
    condition: always()
    jobs:
        
    - template: run-test-template.yml
      parameters:
        jobName: Windows_Edge
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: ${{parameters.deviceName}}
        bsOSVersion: ${{parameters.bsOSVersion}}
        workers:  ${{parameters.workers}}
        bsBrowserVersion: 'latest'
        target: 'Edge'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        isAccessibilityTesting: ${{parameters.isAccessibilityTesting}}
        dependsOn: ''

    - template: generate-Specflow-Report.yml
      parameters:
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.seleniumGrid}}
        dependsOn:
        - Windows_Edge
        projects:
        - PETS_E2E

  - stage: Windows_Firefox
    displayName: Windows_Firefox
    condition: always()
    jobs:
        
    - template: run-test-template.yml
      parameters:
        jobName: Windows_Firefox
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: ${{parameters.deviceName}}
        bsOSVersion: ${{parameters.bsOSVersion}}
        workers:  ${{parameters.workers}}
        bsBrowserVersion: 'latest'
        target: 'Firefox'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        isAccessibilityTesting: ${{parameters.isAccessibilityTesting}}
        dependsOn: ''
        
    - template: generate-Specflow-Report.yml
      parameters:
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.seleniumGrid}}
        dependsOn:
        - Windows_Firefox
        projects:
        - PETS_E2E

  - stage: OSX_Safari_latest
    displayName: OSX_Safari_latest
    condition: always()
    jobs:
    
    - template: run-test-template.yml
      parameters:
        jobName: OSX_Safari_latest
        environment: ${{ parameters.environment}}
        branchName: ${{ parameters.branchName}}
        seleniumGrid: ${{parameters.seleniumGrid}}  
        deviceName: ${{parameters.deviceName}}
        bsOSVersion: ${{parameters.bsOSVersion}}
        workers:  ${{parameters.workers}}
        bsBrowserVersion: 'latest'
        target: 'Safari'
        isEmulationEnabled: ${{parameters.isEmulationEnabled}}
        emulateDeviceInfo: ${{parameters.emulateDeviceInfo}}
        isAccessibilityTesting: ${{parameters.isAccessibilityTesting}}
        dependsOn: ''
    
    - template: generate-Specflow-Report.yml
      parameters:
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.seleniumGrid}}
        dependsOn:
        - OSX_Safari_latest
        projects:
        - PETS_E2E