trigger: none

parameters:
  - name: environment
    type: string
    default: 'pre'

resources:
  repositories:
    - repository: niptsopsprovingrepo
      type: github
      name: DEFRA/nipts-pts-ops-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

variables:
    - template: 'variables/CP/${{ parameters.environment }}.yml'

stages:

  - stage: iOS_iPad13_Safari
    displayName: iPad13_Safari
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: iPad13_Safari
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'iPad Pro 13 2024'
        bsOSVersion: '17'
        workers:  '10'
        bsBrowserVersion: '17'
        target: 'safari'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPad Pro 13 2024'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: iOS_iPad13_Chromium
    displayName: iPad13_Chromium
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: iPad13_Chromium
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'iPad Pro 13 2024'
        bsOSVersion: '17'
        workers:  '10'
        bsBrowserVersion: '17'
        target: 'chromium'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPad Pro 13 2024'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: iOS_iPad12_Safari
    displayName: iPad12_Safari
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: iPad12_Safari
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'iPad Pro 12.9 2022'
        bsOSVersion: '16'
        workers:  '10'
        bsBrowserVersion: '16.1'
        target: 'safari'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: iOS_iPad12_Chromium
    displayName: iPad12_Chromium
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: iPad12_Chromium
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'iPad Pro 12.9 2022'
        bsOSVersion: '16'
        workers:  '10'
        bsBrowserVersion: '16.1'
        target: 'chromium'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: iOS_iPad10_Safari
    displayName: iPad10_Safari
    condition: always()
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: iPad10_Safari
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'iPad 10th'
        bsOSVersion: '16'
        workers:  '10'
        bsBrowserVersion: '16.1'
        target: 'safari'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPad 10th'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: iOS_iPad10_Chromium
    displayName: iPad10_Chromium
    condition: always()
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: iPad10_Chromium
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'iPad 10th'
        bsOSVersion: '16'
        workers:  '10'
        bsBrowserVersion: '16.1'
        target: 'chromium'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPad 10th'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'