trigger: none

parameters:
  - name: environment
    type: string
    default: 'pre'

resources:
  repositories:
    - repository: niptsopsprovingrepo
      type: github
      name: DEFRA/nipts-pts-ops-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

variables:
    - template: 'variables/CP/${{ parameters.environment }}.yml'

stages:
  
  - stage: Android_SamsungGalaxyTabS8_Chrome
    displayName: SamsungGalaxyTabS8_Chrome
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyTabS8_Chrome
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'Samsung Galaxy Tab S8'
        bsOSVersion: '12.0'
        workers:  '10'
        bsBrowserVersion: '12.0'
        target: 'chrome'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'Samsung Galaxy Tab S8'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: Android_SamsungGalaxyTabS8_SamsungInternet
    displayName: SamsungGalaxyTabS8_SamsungInternet
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyTabS8_SamsungInternet
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'Samsung Galaxy Tab S8'
        bsOSVersion: '12.0'
        workers:  '10'
        bsBrowserVersion: '12.0'
        target: 'samsung'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'Samsung Galaxy Tab S8'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: Android_SamsungGalaxyTabS9_Chrome
    displayName: SamsungGalaxyTabS9_Chrome
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyTabS9_Chrome
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'Samsung Galaxy Tab S9'
        bsOSVersion: '13.0'
        workers:  '10'
        bsBrowserVersion: '13.0'
        target: 'chrome'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: Android_SamsungGalaxyTabS9_SamsungInternet
    displayName: SamsungGalaxyTabS9_SamsungInternet
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SamsungGalaxyTabS9_SamsungInternet
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'https://hub.browserstack.com/wd/hub/' 
        deviceName: 'Samsung Galaxy Tab S9'
        bsOSVersion: '13.0'
        workers:  '10'
        bsBrowserVersion: '13.0'
        target: 'samsung'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        dependsOn: ''
        application: 'CP'
        filterTestCases: 'TestCategory=CPCrossBrowser'