trigger: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: 'pre'

resources:
  repositories:
    - repository: niptsopsprovingrepo
      type: github
      name: DEFRA/nipts-pts-ops-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

variables:
    - template: 'variables/CP/${{ parameters.environment }}.yml'

stages:
  
  - stage: Windows_Chrome_latest
    displayName: Windows_Chrome_latest
    condition: always()
  
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: Windows_Chrome_latest
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'http://localhost:4444'
        deviceName: 'Windows'
        bsOSVersion: '11'
        workers:  '10'
        bsBrowserVersion: 'latest'
        target: 'Chrome'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        application: 'CP'
        dependsOn: ''
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: Windows_Edge
    displayName: Windows_Edge
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: Windows_Edge
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'http://localhost:4444'
        deviceName: 'Windows'
        bsOSVersion: '11'
        workers:  '10'
        bsBrowserVersion: 'latest'
        target: 'Edge'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        application: 'CP'
        dependsOn: ''
        filterTestCases: 'TestCategory=CPCrossBrowser'

  - stage: Windows_Firefox
    displayName: Windows_Firefox
    condition: always()

    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: Windows_Firefox
        environment: ${{ parameters.environment}}
        branchName: $(Build.SourceBranch)
        seleniumGrid: 'http://localhost:4444'
        deviceName: 'Windows'
        bsOSVersion: '11'
        workers:  '10'
        bsBrowserVersion: 'latest'
        target: 'Firefox'
        isEmulationEnabled: 'false'
        emulateDeviceInfo: 'iPhone 12 Pro'
        application: 'CP'
        dependsOn: ''
        filterTestCases: 'TestCategory=CPCrossBrowser'