jobs: 

- job: Publish-Accessibility-Report
  displayName: Publish Accessibility Report

  steps:
  
    - task: PowerShell@2
      displayName:  'Copy Accessibility report to Default Directory'
      inputs:
        targetType: 'inline'
        script: |
         $sourcePath= "$(System.DefaultWorkingDirectory)"
         $destinationPath = "$sourcePath\reports"
         if( -not (Test-Path -Path $destinationPath) ) {
            New-Item -ItemType Directory -Path $destinationPath }      

          Get-ChildItem -Path $sourcePath -Filter "*.html" -Recurse | ForEach-Object { 
               if($_.FullName -ne "$destinationPath\$_.FullName") {
                Copy-Item -Path $_.FullName -Destination $destinationPath -Force } }
      
    - task: PublishBuildArtifacts@1 
      displayName: 'Publish Artifact: report-files'
      inputs: 
        PathtoPublish: '$(System.DefaultWorkingDirectory)/reports'
        ArtifactName: 'report-files' 
        publishLocation: 'Container'
  
    
